export enum POKEMON_TYPES {
    NORMAL = 'normal',
    FIGHTING = 'fighting',
    FLYING = 'flying',
    POISON = 'poison',
    GROUND = 'ground',
    ROCK = 'rock',
    BUG = 'bug',
    GHOST = 'ghost',
    STEEL = 'steel',
    FIRE = 'fire',
    WATER = 'water',
    GRASS = 'grass',
    ELECTRIC = 'electric',
    PSYCHIC = 'psychic',
    ICE = 'ice',
    DRAGON = 'dragon',
    DARK = 'dark',
    FAIRY = 'fairy',
    UNKNOWN = 'unknown',
    SHADOW = 'shadow'
}

export enum POKEMON_TYPES_ID {
    NORMAL = 0,
    FIGHTING = 1,
    FLYING = 2,
    POISON = 3,
    GROUND = 4,
    ROCK = 5,
    BUG = 6,
    GHOST = 7,
    STEEL = 8,
    FIRE = 9,
    WATER = 10,
    GRASS = 11,
    ELECTRIC = 12,
    PSYCHIC = 13,
    ICE = 14,
    DRAGON = 15,
    DARK = 16,
    FAIRY = 17,
    UNKNOWN = 18,
    SHADOW = 19
}